env:
  language: php
  php:
    - '5.6'
  matrix:
    - VERSION=7.8.0.0 EDITION=Ult
before_install:
    - curl https://scarlett.sugarondemand.com/custom/hosted/encrypt.tar.enc -o encrypt.tar.enc
    - openssl aes-256-cbc -K $encrypted_3bc6373f0212_key -iv $encrypted_3bc6373f0212_iv -in encrypt.tar.enc -out encrypted.tar -d
    - tar xvf encrypted.tar

before_script:
    - unzip encrypt/Installers/$VERSION/Sugar$EDITION-$VERSION.zip -d sugar &> /dev/null
    - cp SugarRepairsModule/encrypt/config_si.php sugar/config_si.php
    - sudo apt-get install apache2 libapache2-mod-php5
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
    - cat SugarRepairsModule/encrypted/phpenv.txt | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
    - cat SugarRepairsModule/encrypted/vhost.txt | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
    - sudo service apache2 restart
    - mysql -u root -e "CREATE USER 'sugarcrm'@'localhost' IDENTIFIED BY 'sugarcrm'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sugarcrm'@'localhost' WITH GRANT OPTION;"
    - curl 'http://localhost/sugar/install.php?goto=SilentInstall&cli=true'
    - cd tests
#install:
#  - sudo curl -u $FTP_USER:$FTP_PASSWORD $FTP_URL/Files/install.sh -o install.sh
#  - sudo sh install.sh
#  - zip -r installer.zip $TRAVIS_BUILD_DIR
#  - cd /var/www/
#  - sudo curl -u $FTP_USER:$FTP_PASSWORD $FTP_URL/$VERSION/Sugar$EDITION-$VERSION.zip -o sugar.zip
#  - sudo unzip sugar.zip &> /dev/null
#  - cd Sugar$EDITION-Full-$VERSION
#  - sudo curl -u $FTP_USER:$FTP_PASSWORD $FTP_URL/$VERSION/Sugar$EDITION-$VERSION-tests.zip -o tests.zip
#  - sudo unzip tests.zip &> /dev/null
#  - sudo cp -f $TRAVIS_BUILD_DIR/travis-ci/config_si.php .
#  - sudo cp -f $TRAVIS_BUILD_DIR/travis-ci/silentInstall.php .
#  - sudo cp -f $TRAVIS_BUILD_DIR/travis-ci/moduleInstaller.php .
#  - sudo sed -e "s?%SUGAR_KEY%?$SUGAR_KEY?g" --in-place "config_si.php"
#  - sudo chmod -R 777 /var/www/
#  - sudo php silentInstall.php
#  - sudo php moduleInstaller.php -z $TRAVIS_BUILD_DIR/installer.zip
#  - composer install --no-dev
#  - sudo chmod -R 777 /var/www/
#script: cd /var/www/Sugar$EDITION-Full-$VERSION/tests/ && phpunit --group support
#language: php
#php:
#  - '5.4'
#services:
#  - elasticsearch
#  - mysql
#before_install:
#  - sudo apt-get purge elasticsearch #remove latest ES
#  - sudo curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
#  - sudo dpkg -i elasticsearch-1.4.4.deb #install a supported version of ES
#  - sudo /etc/init.d/elasticsearch start
##install:
#before_script:
#  - echo 'date.timezone = "America/New_York"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - echo 'max_execution_time = 600' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - echo 'memory_limit = 512M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - sudo zip -r installer.zip $TRAVIS_BUILD_DIR
#  - echo "USE mysql; UPDATE user SET password=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root #force password
#  - sudo apt-get update
#  - sudo apt-get install apache2 libapache2-mod-fastcgi
#  # enable php-fpm
#  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
#  - sudo a2enmod rewrite actions fastcgi alias
#  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
#  # install apache
#  - sudo cp -f travis-ci/travis-ci-apache "/etc/apache2/sites-available/default"
#  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place "/etc/apache2/sites-available/default"
#  - sudo service apache2 restart
#  - sleep 10
#  # install sugar
#  - sudo curl -u $FTP_USER:$FTP_PASSWORD $FTP_URL/$VERSION/Sugar$EDITION-$VERSION.zip -o sugar.zip
#  - sudo unzip sugar.zip &> /dev/null
#  - cd Sugar$EDITION-Full-$VERSION
#  - sudo curl -u $FTP_USER:$FTP_PASSWORD $FTP_URL/$VERSION/Sugar$EDITION-$VERSION-tests.zip -o tests.zip
#  - sudo unzip tests.zip &> /dev/null
#  - sudo chmod -R 777 $TRAVIS_BUILD_DIR
#  - sudo cp -f $TRAVIS_BUILD_DIR/travis-ci/config_si.php .
#  - sudo sed -e "s?%SUGAR_KEY%?$SUGAR_KEY?g" --in-place "config_si.php"
#  - sudo cp -f $TRAVIS_BUILD_DIR/travis-ci/silentInstall.php .
#  - sudo php silentInstall.php
#  - sudo cp -f $TRAVIS_BUILD_DIR/travis-ci/moduleInstaller.php .
#  - sudo php moduleInstaller.php -z $TRAVIS_BUILD_DIR/installer.zip
#  - composer install --no-dev
script: cd sugar/tests/ && phpunit --group support
