language: php

services:
  - elasticsearch
  - mysql

matrix:
  include:
  - php: "5.6"
    env: VERSION=7.8.0.0 EDITION=Ent TESTS=7.8
  - php: "5.6"
    env: VERSION=7.8.0.0 EDITION=Pro TESTS=7.8
  - php: "5.6"
    env: VERSION=7.7.2.0 EDITION=Ent TESTS=7.7
  - php: "5.6"
    env: VERSION=7.7.2.0 EDITION=Pro TESTS=7.7
  - php: "5.3"
    env: VERSION=7.8.0.0 EDITION=Ent TESTS=7.8
  - php: "5.3"
    env: VERSION=7.8.0.0 EDITION=Pro TESTS=7.8
  - php: "5.3"
    env: VERSION=7.7.2.0 EDITION=Ent TESTS=7.7
  - php: "5.3"
    env: VERSION=7.7.2.0 EDITION=Pro TESTS=7.7
  - php: "5.3"
    env: VERSION=6.5.24 EDITION=Ent TESTS=6.5
  - php: "5.3"
    env: VERSION=6.5.24 EDITION=Pro TESTS=6.5
    
before_install:
    - echo "error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo apt-get purge elasticsearch #remove latest ES
    - sudo curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
    - sudo dpkg -i --force-confnew elasticsearch-1.4.4.deb #install a supported version of ES
    - sudo service elasticsearch restart
    - curl https://scarlett.sugarondemand.com/custom/hosted/encrypt.tar.gz.enc -o encrypt.tar.gz.enc
    - openssl aes-256-cbc -K $encrypted_3bc6373f0212_key -iv $encrypted_3bc6373f0212_iv -in encrypt.tar.gz.enc -out encrypt.tar.gz -d
    - tar -xzvf encrypt.tar.gz

before_script:
    - php build.php --name package
    - unzip encrypt/Installers/$VERSION/Sugar$EDITION-$VERSION.zip &> /dev/null
    - cp -R encrypt/Tests/$TESTS/ Sugar$EDITION-Full-$VERSION/tests/
    - cp .travis/config_si.php Sugar$EDITION-Full-$VERSION/config_si.php
    - cp .travis/cliSilentInstall.php Sugar$EDITION-Full-$VERSION/cliSilentInstall.php
    - mysql -u root -e "CREATE USER 'sugarcrm'@'localhost' IDENTIFIED BY 'sugarcrm'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sugarcrm'@'localhost' WITH GRANT OPTION;"
    - sudo chmod -R 777 Sugar$EDITION-Full-$VERSION
    - cd Sugar$EDITION-Full-$VERSION
    - sleep 10 #for elasticsearch
    - php cliSilentInstall.php
    - php $TRAVIS_BUILD_DIR/.travis/cliModuleInstall.php -i $TRAVIS_BUILD_DIR/Sugar$EDITION-Full-$VERSION -z $TRAVIS_BUILD_DIR/builds/package.zip
    - composer install
    - sudo chmod -R 777 .

script: cd tests/ && ../vendor/phpunit/phpunit/phpunit --verbose --debug --group support --stop-on-failure
