<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN supp_SugarRepairs
 */

require_once 'include/SugarObjects/templates/issue/Issue.php';

class supp_SugarRepairs_sugar extends Issue {
    public $new_schema = true;
    public $module_dir = 'supp_SugarRepairs';
    public $object_name = 'supp_SugarRepairs';
    public $table_name = 'supp_sugarrepairs';
    public $importable = false;
        public $disable_row_level_security = true;
    
    /**
     * This is a deprecated method, please start using __construct() as this
     * method will be removed in a future version.
     *
     * @see __construct
     * @deprecated
     */
    public function supp_SugarRepairs_sugar(){
        $GLOBALS['log']->deprecated('Calls to supp_SugarRepairs::supp_SugarRepairs are deprecated.');
        self::__construct();
    }

    public function __construct(){
        parent::__construct();
    }
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}